version: "3.8"

services:
  hill_climbing_solver:
    container_name: hill_climbing_solver
    build:
      context: hill_climbing_solver_container/.
      dockerfile: production.Dockerfile
    image: joseesco24/hill_climbing_solver
    networks:
      - general_solvers_functions_network
    environment:
      FITNESS_SINGLE_SCORE_LINK: ${FITNESS_SINGLE_SCORE_LINK}
      FITNESS_REPORT_SCORE_LINK: ${FITNESS_REPORT_SCORE_LINK}
      RANDOM_INITIALIZATION_LINK: ${RANDOM_INITIALIZATION_LINK}
      RANDOM_MUTATION_LINK: ${RANDOM_MUTATION_LINK}
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      HILL_CLIMBING_SOLVER_KEY: ${HILL_CLIMBING_SOLVER_KEY}
      ACCESS_PORT: ${HILL_CLIMBING_SOLVER_PORT}
    ports:
      - target: ${HILL_CLIMBING_SOLVER_PORT}
        published: ${SERVICE_ACCESS_PORT}
        protocol: tcp
    depends_on:
      - general_solvers_functions
    entrypoint: ["python", "-u", "api_server.py"]

  general_solvers_functions:
    container_name: general_solvers_functions
    build:
      context: general_solvers_functions_container/.
      dockerfile: production.Dockerfile
    image: joseesco24/general_solvers_functions
    networks:
      - general_solvers_functions_network
    environment:
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      ACCESS_PORT: ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    expose:
      - ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    entrypoint: ["python", "-u", "api_server.py"]

networks:
  general_solvers_functions_network:
    name: general_solvers_functions_network
    external: false
    driver: bridge
