version: "3.8"

services:

  hill_climbing_solver:
    container_name: hill_climbing_solver
    image: joseesco24/hill_climbing_solver
    build:
      context: hill_climbing_solver_container/.
      dockerfile: production.Dockerfile
    networks:
      - general_solvers_functions_network
      - main_proxy_gateway_network
    environment:
      FITNESS_SINGLE_SCORE_LINK: ${FITNESS_SINGLE_SCORE_LINK}
      FITNESS_REPORT_SCORE_LINK: ${FITNESS_REPORT_SCORE_LINK}
      RANDOM_INITIALIZATION_LINK: ${RANDOM_INITIALIZATION_LINK}
      RANDOM_MUTATION_LINK: ${RANDOM_MUTATION_LINK}
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      HILL_CLIMBING_SOLVER_KEY: ${HILL_CLIMBING_SOLVER_KEY}
      ACCESS_PORT: ${HILL_CLIMBING_SOLVER_PORT}
    expose:
      - ${HILL_CLIMBING_SOLVER_PORT}
    depends_on:
      - general_solvers_functions
      - main_proxy_gateway
    entrypoint: ["python", "-u", "api_server.py"]

  main_proxy_gateway:
    container_name: main_proxy_gateway
    image: joseesco24/main_proxy_gateway
    build:
      context: main_proxy_gateway_container/.
      dockerfile: production.Dockerfile
    networks:
      - main_proxy_gateway_network
    environment:
      HILL_CLIMBING_SOLVER_LINK: ${HILL_CLIMBING_SOLVER_LINK}
      HILL_CLIMBING_SOLVER_KEY: ${HILL_CLIMBING_SOLVER_KEY}
      ACCESS_PORT: ${MAIN_PROXY_GATEWAY_PORT}
    ports:
      - target: ${MAIN_PROXY_GATEWAY_PORT}
        published: ${HOST_ACCESS_PORT}
        protocol: tcp

  general_solvers_functions:
    container_name: general_solvers_functions
    image: joseesco24/general_solvers_functions
    build:
      context: general_solvers_functions_container/.
      dockerfile: production.Dockerfile
    networks:
      - general_solvers_functions_network
    environment:
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      ACCESS_PORT: ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    expose:
      - ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    entrypoint: ["python", "-u", "api_server.py"]

networks:
  general_solvers_functions_network:
    name: general_solvers_functions_network
    external: false
    driver: bridge
  main_proxy_gateway_network:
    name: main_proxy_gateway_network
    external: false
    driver: bridge
