version: "3.8"

services:
  main_proxy:
    container_name: main_proxy
    image: joseesco24/main_proxy
    build:
      context: container_main_proxy/.
      dockerfile: production.Dockerfile
    networks:
      - middle_proxy_network
    environment:
      MIDDLE_PROXY_CONTAINER_1: ${MIDDLE_PROXY_CONTAINER_1}
      MIDDLE_PROXY_CONTAINER_2: ${MIDDLE_PROXY_CONTAINER_2}
      MIDDLE_PROXY_CONTAINER_3: ${MIDDLE_PROXY_CONTAINER_3}
      ACCESS_PORT: ${MAIN_PROXY_PORT}
    ports:
      - target: ${MAIN_PROXY_PORT}
        published: ${HOST_ACCESS_PORT}
        protocol: tcp
    depends_on:
      - middle_proxy_1
      - middle_proxy_2
      - middle_proxy_3

  middle_proxy_1:
    container_name: middle_proxy_1
    image: joseesco24/middle_proxy
    build:
      context: container_middle_proxy/.
      dockerfile: production.Dockerfile
    networks:
      - solved_boards_database_network
      - middle_proxy_network
      - solvers_network
    environment:
      HILL_CLIMBING_SOLVER_HEALTH_TEST_LINK: ${HILL_CLIMBING_SOLVER_HEALTH_TEST_LINK}
      GENETIC_ALGORITHM_SOLVER_HEALTH_TEST_LINK: ${GENETIC_ALGORITHM_SOLVER_HEALTH_TEST_LINK}
      GENETIC_ALGORITHM_SOLVER_LINK: ${GENETIC_ALGORITHM_SOLVER_LINK}
      HILL_CLIMBING_SOLVER_LINK: ${HILL_CLIMBING_SOLVER_LINK}
      GENETIC_ALGORITHM_SOLVER_KEY: ${GENETIC_ALGORITHM_SOLVER_KEY}
      HILL_CLIMBING_SOLVER_KEY: ${HILL_CLIMBING_SOLVER_KEY}
      ACCESS_PORT: ${MIDDLE_PROXY_PORT}
      ACCESS_KEY: ${MIDDLE_PROXY_KEY}
    expose:
      - ${MIDDLE_PROXY_PORT}
    depends_on:
      - genetic_algorithm_solver
      - hill_climbing_solver
    entrypoint: ["node", "api_server.mjs"]

  middle_proxy_2:
    container_name: middle_proxy_2
    image: joseesco24/middle_proxy
    build:
      context: container_middle_proxy/.
      dockerfile: production.Dockerfile
    networks:
      - solved_boards_database_network
      - middle_proxy_network
      - solvers_network
    environment:
      HILL_CLIMBING_SOLVER_HEALTH_TEST_LINK: ${HILL_CLIMBING_SOLVER_HEALTH_TEST_LINK}
      GENETIC_ALGORITHM_SOLVER_HEALTH_TEST_LINK: ${GENETIC_ALGORITHM_SOLVER_HEALTH_TEST_LINK}
      GENETIC_ALGORITHM_SOLVER_LINK: ${GENETIC_ALGORITHM_SOLVER_LINK}
      HILL_CLIMBING_SOLVER_LINK: ${HILL_CLIMBING_SOLVER_LINK}
      GENETIC_ALGORITHM_SOLVER_KEY: ${GENETIC_ALGORITHM_SOLVER_KEY}
      HILL_CLIMBING_SOLVER_KEY: ${HILL_CLIMBING_SOLVER_KEY}
      ACCESS_PORT: ${MIDDLE_PROXY_PORT}
      ACCESS_KEY: ${MIDDLE_PROXY_KEY}
    expose:
      - ${MIDDLE_PROXY_PORT}
    depends_on:
      - genetic_algorithm_solver
      - hill_climbing_solver
    entrypoint: ["node", "api_server.mjs"]

  middle_proxy_3:
    container_name: middle_proxy_3
    image: joseesco24/middle_proxy
    build:
      context: container_middle_proxy/.
      dockerfile: production.Dockerfile
    networks:
      - solved_boards_database_network
      - middle_proxy_network
      - solvers_network
    environment:
      HILL_CLIMBING_SOLVER_HEALTH_TEST_LINK: ${HILL_CLIMBING_SOLVER_HEALTH_TEST_LINK}
      GENETIC_ALGORITHM_SOLVER_HEALTH_TEST_LINK: ${GENETIC_ALGORITHM_SOLVER_HEALTH_TEST_LINK}
      GENETIC_ALGORITHM_SOLVER_LINK: ${GENETIC_ALGORITHM_SOLVER_LINK}
      HILL_CLIMBING_SOLVER_LINK: ${HILL_CLIMBING_SOLVER_LINK}
      GENETIC_ALGORITHM_SOLVER_KEY: ${GENETIC_ALGORITHM_SOLVER_KEY}
      HILL_CLIMBING_SOLVER_KEY: ${HILL_CLIMBING_SOLVER_KEY}
      ACCESS_PORT: ${MIDDLE_PROXY_PORT}
      ACCESS_KEY: ${MIDDLE_PROXY_KEY}
    expose:
      - ${MIDDLE_PROXY_PORT}
    depends_on:
      - genetic_algorithm_solver
      - hill_climbing_solver
    entrypoint: ["node", "api_server.mjs"]

  hill_climbing_solver:
    container_name: hill_climbing_solver
    image: joseesco24/hill_climbing_solver
    build:
      context: hill_climbing_solver_container/.
      dockerfile: production.Dockerfile
    networks:
      - solved_boards_database_network
      - main_load_balancer_network
      - solvers_network
    environment:
      FITNESS_SINGLE_SCORE_LINK: ${FITNESS_SINGLE_SCORE_LINK_LB}
      FITNESS_REPORT_SCORE_LINK: ${FITNESS_REPORT_SCORE_LINK_LB}
      RANDOM_INITIALIZATION_LINK: ${RANDOM_INITIALIZATION_LINK_LB}
      RANDOM_MUTATION_LINK: ${RANDOM_MUTATION_LINK_LB}
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      ACCESS_PORT: ${HILL_CLIMBING_SOLVER_PORT}
      ACCESS_KEY: ${HILL_CLIMBING_SOLVER_KEY}
    expose:
      - ${HILL_CLIMBING_SOLVER_PORT}
    depends_on:
      - main_load_balancer
    entrypoint: ["python", "-u", "api_server.py"]

  genetic_algorithm_solver:
    container_name: genetic_algorithm_solver
    image: joseesco24/genetic_algorithm_solver
    build:
      context: genetic_algorithm_solver_container/.
      dockerfile: production.Dockerfile
    networks:
      - solved_boards_database_network
      - main_load_balancer_network
      - solvers_network
    environment:
      FITNESS_SINGLE_SCORE_LINK: ${FITNESS_SINGLE_SCORE_LINK_LB}
      FITNESS_REPORT_SCORE_LINK: ${FITNESS_REPORT_SCORE_LINK_LB}
      RANDOM_INITIALIZATION_LINK: ${RANDOM_INITIALIZATION_LINK_LB}
      RANDOM_MUTATION_LINK: ${RANDOM_MUTATION_LINK_LB}
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      ACCESS_PORT: ${GENETIC_ALGORITHM_SOLVER_PORT}
      ACCESS_KEY: ${GENETIC_ALGORITHM_SOLVER_KEY}
    expose:
      - ${GENETIC_ALGORITHM_SOLVER_PORT}
    depends_on:
      - main_load_balancer
    entrypoint: ["python", "-u", "api_server.py"]

  main_load_balancer:
    container_name: main_load_balancer
    image: joseesco24/main_load_balancer
    build:
      context: main_load_balancer_container/.
      dockerfile: production.Dockerfile
    networks:
      - general_solvers_functions_network
      - main_load_balancer_network
    environment:
      GENERAL_SOLVERS_FUNCTIONS_SERVER_1: ${GENERAL_SOLVERS_FUNCTIONS_SERVER_1}
      GENERAL_SOLVERS_FUNCTIONS_SERVER_2: ${GENERAL_SOLVERS_FUNCTIONS_SERVER_2}
      GENERAL_SOLVERS_FUNCTIONS_SERVER_3: ${GENERAL_SOLVERS_FUNCTIONS_SERVER_3}
      ACCESS_PORT: ${MAIN_LOAD_BALANCER_PORT}
    expose:
      - ${MAIN_LOAD_BALANCER_PORT}
    depends_on:
      - general_solvers_functions_1
      - general_solvers_functions_2
      - general_solvers_functions_3

  general_solvers_functions_1:
    container_name: general_solvers_functions_1
    image: joseesco24/general_solvers_functions
    build:
      context: general_solvers_functions_container/.
      dockerfile: production.Dockerfile
    networks:
      - general_solvers_functions_network
    environment:
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      ACCESS_PORT: ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    expose:
      - ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    entrypoint: ["python", "-u", "api_server.py"]

  general_solvers_functions_2:
    container_name: general_solvers_functions_2
    image: joseesco24/general_solvers_functions
    build:
      context: general_solvers_functions_container/.
      dockerfile: production.Dockerfile
    networks:
      - general_solvers_functions_network
    environment:
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      ACCESS_PORT: ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    expose:
      - ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    entrypoint: ["python", "-u", "api_server.py"]

  general_solvers_functions_3:
    container_name: general_solvers_functions_3
    image: joseesco24/general_solvers_functions
    build:
      context: general_solvers_functions_container/.
      dockerfile: production.Dockerfile
    networks:
      - general_solvers_functions_network
    environment:
      GENERAL_SOLVER_FUNCTIONS_KEY: ${GENERAL_SOLVER_FUNCTIONS_KEY}
      ACCESS_PORT: ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    expose:
      - ${GENERAL_SOLVERS_FUNCTIONS_PORT}
    entrypoint: ["python", "-u", "api_server.py"]

networks:
  general_solvers_functions_network:
    name: general_solvers_functions_network
    external: false
    driver: bridge

  solved_boards_database_network:
    name: solved_boards_database_network
    external: false
    driver: bridge

  middle_proxy_network:
    name: middle_proxy_network
    external: false
    driver: bridge

  main_load_balancer_network:
    name: main_load_balancer_network
    external: false
    driver: bridge

  solvers_network:
    name: solvers_network
    external: false
    driver: bridge
